<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7baa393a-a7dd-4f77-9dce-19fe405013c8</UserSecretsId>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AJP.Aspire.Hosting.AsbEmulatorUi" Version="1.0.24" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.1" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.2.1" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pub\Pub.csproj" />
    <ProjectReference Include="..\Sub\Sub.csproj" />
  </ItemGroup>

</Project>
