# dapr/configuration/global_config.yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: global_config
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://localhost:18889"
  metrics:
    enabled: true
  # features:
  # - name: Workflow
  #   enabled: true
  accessControl:    
    policies:
    - appId: pub-app-id
      defaultAction: allow
      namespace: default
      trustDomain: public
    - appId: sub-app-id
      defaultAction: allow
      namespace: default
      trustDomain: public