apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
spec:
  policies:
    retries:
      actorRetry:
        policy: constant
        duration: 2s
        maxRetries: 3

      pubsubRetry:
        policy: exponential
        duration: 10s
        maxInterval: 60s
        maxRetries: 5

    timeouts:
      pubsubTimeout: 30s

    circuitBreakers:
      pubsubCB:
        maxRequests: 1
        interval: 30s
        timeout: 30s
        trip: consecutiveFailures >= 5

  targets:
    actors:
      MessageHandlerActor:
        retry: actorRetry

    components:
      servicebus_pubsub:
        outbound:
          retry: pubsubRetry
          timeout: pubsubTimeout
          circuitBreaker: pubsubCB
