apiVersion: dapr.io/v1
kind: Component
metadata:
  name: servicebus
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      env: AzureServiceBus__ConnectionString
